# Generated by Django 5.2.5 on 2025-08-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('hash_password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('profile_picture', models.CharField(max_length=50)),
                ('status', models.PositiveSmallIntegerField()),
                ('creation_date', models.DateTimeField()),
                ('birth_date', models.DateTimeField()),
                ('institutional_id', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('program', models.CharField(max_length=50)),
                ('section_id', models.IntegerField()),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
            ],
        ),
    ]
