# Generated by Django 5.2.5 on 2025-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='profile',
            new_name='admin_id',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='profile',
            new_name='faculty_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='profile',
            new_name='staff_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='profile',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='id',
        ),
        migrations.AddField(
            model_name='position',
            name='position_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='section',
            name='section_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
