# Generated by Django 5.2.5 on 2025-09-04 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_admin_admin_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.OneToOneField(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.OneToOneField(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.OneToOneField(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.profile'),
        ),
    ]
