# Generated by Django 5.2.5 on 2025-09-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_admin_admin_id_alter_faculty_faculty_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_department',
        ),
    ]
