# Generated by Django 5.2.5 on 2025-09-04 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_faculty_faculty_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='position',
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.facultydepartment'),
        ),
    ]
